#!/usr/bin/env php

<?php
error_reporting(E_ALL);

/* Get the port for the WWW service. */
$port = 9503;

/* Get the IP address for the target host. */
$address = "192.168.1.11";

/* Create a TCP/IP socket. */
$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
if ($socket === false) {
    echo "socket_create() failed: reason: " . socket_strerror(socket_last_error()) . "\n";
}

echo "Attempting to connect to '$address' on port '$port'...";
$result = socket_connect($socket, $address, $port);
if ($result === false) {
    echo "socket_connect() failed.\nReason: ($result) " . socket_strerror(socket_last_error($socket)) . "\n";
} else {
    echo "OK.\n";
}

$in = "Hello world"; 
$out = '';

echo "Sending request...";
socket_write($socket, $in, strlen($in));
echo "OK.\n";

echo "Reading response: ";
while ($out = socket_read($socket, 2048)) {
    echo $out;
}
echo "\n";

echo "Closing socket...";
socket_close($socket);
echo "OK.\n\n";
?>
